name: spring app cicd with AWS EKS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "21"

      - name: Build and Test
        working-directory: ./demo
        run: mvn -B clean verify

      - name: Upload Test Reports
        uses: actions/upload-artifact@v7
        with:
          name: test-reports
          path: ./target/surefire-reports

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout-code
        uses: actions/checkout@v7

      - name: Setup JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "21"

      - name: Build JAR for Docker
        working-directory: ./demo
        run: mvn -B clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v7
        with:
          context: ./demo
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/spring-app:latest

  deploy-aws-eks:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup and Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4

      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name hello-cluster --region ap-south-1

      - name: Verify Connection
        run: kubectl get nodes

      - name: Deploy to AWS EKS
        run: |
          kubectl apply -f ./k8s
          kubectl rollout restart deployment/app-deployment
          kubectl rollout status deployment/app-deployment
